### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by evanthebouncy** [shubhamck/PolicyGradient#1]
Your actor is basically supervised learning from state-action to advantage right (with the weighted edlidgibility), but basically supervised as ur critic tells you the true value of a certain action via advantage.

How is your critic being trained? Is it some kind of TD-learning? That's the problem I havn't figured out from looking at your code.

thanks!

**Comment by shubhamck** [comment]
Yes the critic is trained using TD. So the critic output is the baseline or estimated value of that state. But I calculate the value of the state by calculating the discounted rewards from that state in line 96 of policygradient.py. So I want to minimize the difference between the estimated value and the calculated value for the critic to correctly predict value of the state. Therefore I feed the squared difference of them while training critic.

For reference I calculate baseline in line 101 of policygradient.py

I know the code is messy because it was my first time executing policy gradients. I hope it helps. I will clean up the code once I get time. 

Thanks

**Comment by evanthebouncy** [comment]
okay i got it. you do basically TD-0 or something with 1 step roll-out for the critic, and use the critic to guide the agent over the trace distribution generated by the agent.

I am working on a policy gradient agent using simple roll-out (i.e. no critic) to estimate the Q value. I'll let you know how it goes. Thanks! and good luck with ur projects!!
